name: Homegear-Stable
version: 1.0.0.1
slug: homegear_stable
description: Homegear as a HomeAssistant add-on
arch:
  - armv7
  - armhf
  - aarch64
startup: services
boot: auto
webui: http://[HOST]:[PORT:2001]
ingress: true
ingress_port: 443
panel_icon: mdi:thermostat-box
panel_title: HomegearStable
uart: true
gpio: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
map:
  - config:rw
  - share:rw
ports:
  80: '8080'
  443: '8443'
ports_description:
  80: No SSL
  443: SSL, authentication enabled
environment: {}
options: {}
schema: {}
